os: osx
language: c

install:
  - curl https://nixos.org/nix/install | sh
  - source $HOME/.nix-profile/etc/profile.d/nix.sh
  - git clone https://github.com/nixos/nixpkgs --depth 1
  - export NIX_PATH=nixpkgs=$(pwd)/nixpkgs

script:
  - nix-build env.nix -j 4 --keep-going

cache:
  directories:
    - /nix/store