name: "nix-build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - run: sudo rm -rf /opt /usr/local || true
    - uses: cachix/cachix-action@v5
      with:
        name: utdemir
        file: nix/ci.nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
